### ISSUE TITLE
Title of the study

### ISSUE THREAD

**Issue by ghost** [Daniel-Jomaa/Crypto-Rebalance-Bot#1]
Hi,

What is the title of the study that you're referencing in your readme?

**Comment by Daniel-Jomaa** [comment]
https://blog.shrimpy.io/blog/a-comparison-of-rebalancing-strategies-for-cryptocurrency-portfolios

**Comment by ghost** [comment]
Thanks. Is this code still functional?

**Comment by Daniel-Jomaa** [comment]
the API endpoints might be outdated and the tickers are hardcoded but i think it still does

**Comment by ghost** [comment]
Ok, I'll see if I can get it to work, thank you.
